### PR TITLE
Update charlesbot and install all the current plugins separately

### PR DESCRIPTION
**Pull request by marvinpinto**

### CODE REVIEW

**Comment by minichate** [comment]
Usually these types of dependencies are installed via a `requirements.txt` file. Is there one available that you could use?

**Comment by marvinpinto** [comment]
I think `requirements.txt` would be a great idea!

(this route was the route of laziness :disappointed:)

**Comment by minichate** [comment]
Ohh I see! These are _plugins_ for `charlesbot`, not direct dependencies. OK; in that case leaving it as is kinda makes sense. 

I was derping around https://github.com/marvinpinto/charlesbot/blob/master/requirements.txt and trying to figure out why they didn't match up :D

**Comment by marvinpinto** [comment]
hehe yeah, I converted all those into their separate plugins to make it easier to maintain and that sort of thing :smile:

**Pull request merged**
